theme: jekyll-theme-hacker
title: Chess Image Generation: Synthetic to Real
description: project description goes here

authors:
  alice:
    name: Alice Smith
    role: Backend
    email: alice@example.com
    github: alicesmith
  bob:
    name: Bob Johnson
    role: Frontend
    email: bob@example.com
    github: bobjohnson
  carol:
    name: Carol Lee
    role: DevOps
    email: carol@example.com
    github: carollee
