# Site settings
title: My Awesome Site
description: "A simple blog using Jekyll and Minima"
url: "https://username.github.io"   # Replace with your GitHub username URL
baseurl: ""                         # Leave empty for user/organization pages

# Theme
theme: minima

# Author
author:
  name: Guy, Maor, Yoav
  email: your-email@example.com, ex2@m.com

# Social links
social:
  github: username
  twitter: yourhandle

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed      # optional: generates RSS feed
