theme: jekyll-theme-hacker
title: Chess Image Generation: Synthetic to Real
description: project description goes here

author:
  name: Your Name
  email: you@example.com
github_username: yourusername

author:
  name: Your Name2
  email: you2@example.com
github_username: yourusername2
